sudo: false
dist: trusty

before_script:
  - npm install colors drafter.js glob hercule

script:
  - make rebuild HERCULE=./node_modules/hercule/bin/hercule
  - bash .travis_ensure_compiled.sh
  - node validate.js
