### Calendars [/calendar/calendar]

#### Retrieve a calendar collection [GET]

+ Attributes
        + `start` (number) - Fetch events starting from a date (an integer computed by the difference in days between the date and 01/01/1970).
        + `length` (number) - How many days to fetch.
        + `cal_ids` `_H~C_Bn.J` (string):

            Specify the calendars to fetch with `calendar_ids` encoded by `Range Codec`.

        + `time_zone` Etc/UTC (string):

            Specify the time zone for the events.

+ Request Retrieve only the calendar collection (application/json)

        {}

+ Response 200 (application/json)

        {
            "filter": {
                "enabled": [
                    7,
                    113,
                    110,
                    8
                ],
                "userSetting": [0]
            },
            "cal_info": [
                {
                    "id": 7,
                    "owner_type": "User",
                    "name": "jasmine.green",
                    "owner_id": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "owner_name": "Personal",
                    "display_name": "jasmine.green (Personal)",
                    "can_manage": true,
                    "can_create_event": true
                },
                {
                    "id": 113,
                    "owner_type": "User",
                    "name": "A new personal calendar",
                    "owner_id": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "owner_name": "Personal",
                    "display_name": "A new personal calendar (Personal)",
                    "can_manage": true,
                    "can_create_event": true
                },
                {
                    "id": 110,
                    "owner_type": "Space",
                    "name": "hihihih",
                    "owner_id": "326ee7a7-2c7c-4af0-9eb6-3f79b90dae92",
                    "owner_name": "hihihih",
                    "display_name": "hihihih (hihihih)",
                    "can_manage": true,
                    "can_create_event": true
                },
                {
                    "id": 8,
                    "owner_type": "Space",
                    "name": "The Earth",
                    "owner_id": "b1d9b3bf-6cef-44c3-9382-4b32f7f2cd79",
                    "owner_name": "Peter Tam",
                    "display_name": "The Earth (Universe)",
                    "can_manage": true,
                    "can_create_event": true
                }
            ],
            "spaces_permission": {
                "326ee7a7-2c7c-4af0-9eb6-3f79b90dae92": true,
                "b1d9b3bf-6cef-44c3-9382-4b32f7f2cd79": true
            },
            "requested_at": 847475124
        }

+ Request Retrieve events in the calendar collection (application/json)

        {
            "start": 17465,
            "length": 15,
            "cal_ids": "_H~C_Bn.J",
            "time_zone": "Etc/UTC"
        }

+ Response 200 (application/json)

        {
            "head_events": [
                {
                    "id": 2,
                    "name": "My first recurrence",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": true,
                    "head_id": null,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "2",
                    "my_note": "",
                    "old_head_id": null,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-07T08:00:00.000Z",
                    "utc_finish": "2017-11-07T09:00:00.000Z",
                    "utc_old_start": null,
                    "utc_old_finish": null,
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508399939
                },
                {
                    "id": 64,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": true,
                    "head_id": null,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-11-15",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": null,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-08T08:30:00.000Z",
                    "utc_finish": "2017-11-08T09:30:00.000Z",
                    "utc_old_start": null,
                    "utc_old_finish": null,
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508402510
                },
                {
                    "id": 75,
                    "name": "Another recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": true,
                    "head_id": null,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-14",
                    "repeat_every": 1,
                    "repeat_by": "4",
                    "my_note": "",
                    "old_head_id": null,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-09T00:00:00.000Z",
                    "utc_finish": "2017-11-09T00:00:00.000Z",
                    "utc_old_start": null,
                    "utc_old_finish": null,
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508406018
                },
                {
                    "id": 112,
                    "name": "test",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": true,
                    "head_id": null,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "4,
                    5,
                    6",
                    "my_note": "",
                    "old_head_id": null,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-10-26T07:30:00.000Z",
                    "utc_finish": "2017-10-26T08:30:00.000Z",
                    "utc_old_start": null,
                    "utc_old_finish": null,
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509002371
                }
            ],
            "indices": {
                "17465": [113],
                "17466": [114],
                "17467": [115],
                "17468": [174],
                "17469": [],
                "17470": [],
                "17471": [],
                "17472": [116],
                "17473": [117],
                "17474": [118],
                "17475": [],
                "17476": [],
                "17477": [1,3],
                "17478": [65],
                "17479": [82,119]
            },
            "events": [
                {
                    "id": 1,
                    "name": "My first event!!! (Edited)",
                    "description": "",
                    "where": "",
                    "all_day": true,
                    "recurring_type": "not_repeat",
                    "my_note": "",
                    "old_head_id": null,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-07T12:00:00.000Z",
                    "utc_finish": "2017-11-07T13:00:00.000Z",
                    "utc_old_start": null,
                    "utc_old_finish": null,
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508401619
                },
                {
                    "id": 3,
                    "name": "My first recurrence",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 2,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "2",
                    "my_note": "",
                    "old_head_id": 2,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-07T08:00:00.000Z",
                    "utc_finish": "2017-11-07T09:00:00.000Z",
                    "utc_old_start": "2017-11-07T08:00:00.000Z",
                    "utc_old_finish": "2017-11-07T09:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508399939
                },
                {
                    "id": 65,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 64,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-11-15",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 64,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-08T08:30:00.000Z",
                    "utc_finish": "2017-11-08T09:30:00.000Z",
                    "utc_old_start": "2017-11-08T08:30:00.000Z",
                    "utc_old_finish": "2017-11-08T09:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508400561
                },
                {
                    "id": 82,
                    "name": "Another recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 75,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-14",
                    "repeat_every": 1,
                    "repeat_by": "4",
                    "my_note": "",
                    "old_head_id": 75,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-09T00:00:00.000Z",
                    "utc_finish": "2017-11-09T00:00:00.000Z",
                    "utc_old_start": "2017-11-09T00:00:00.000Z",
                    "utc_old_finish": "2017-11-09T00:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508406018
                },
                {
                    "id": 113,
                    "name": "test",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 112,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "4,5,6",
                    "my_note": "",
                    "old_head_id": 112,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-10-26T07:30:00.000Z",
                    "utc_finish": "2017-10-26T08:30:00.000Z",
                    "utc_old_start": "2017-10-26T07:30:00.000Z",
                    "utc_old_finish": "2017-10-26T08:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509002371
                },
                {
                    "id": 114,
                    "name": "test",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 112,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "4,5,6",
                    "my_note": "",
                    "old_head_id": 112,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-10-27T07:30:00.000Z",
                    "utc_finish": "2017-10-27T08:30:00.000Z",
                    "utc_old_start": "2017-10-27T07:30:00.000Z",
                    "utc_old_finish": "2017-10-27T08:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509002371
                },
                {
                    "id": 115,
                    "name": "test",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 112,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "4,5,6",
                    "my_note": "",
                    "old_head_id": 112,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-10-28T07:30:00.000Z",
                    "utc_finish": "2017-10-28T08:30:00.000Z",
                    "utc_old_start": "2017-10-28T07:30:00.000Z",
                    "utc_old_finish": "2017-10-28T08:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509002371
                },
                {
                    "id": 116,
                    "name": "test",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 112,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "4,5,6",
                    "my_note": "",
                    "old_head_id": 112,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-02T07:30:00.000Z",
                    "utc_finish": "2017-11-02T08:30:00.000Z",
                    "utc_old_start": "2017-11-02T07:30:00.000Z",
                    "utc_old_finish": "2017-11-02T08:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509002372
                },
                {
                    "id": 117,
                    "name": "test",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 112,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "4,5,6",
                    "my_note": "",
                    "old_head_id": 112,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-03T07:30:00.000Z",
                    "utc_finish": "2017-11-03T08:30:00.000Z",
                    "utc_old_start": "2017-11-03T07:30:00.000Z",
                    "utc_old_finish": "2017-11-03T08:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509002372
                },
                {
                    "id": 118,
                    "name": "test",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 112,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "4,5,6",
                    "my_note": "",
                    "old_head_id": 112,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-04T07:30:00.000Z",
                    "utc_finish": "2017-11-04T08:30:00.000Z",
                    "utc_old_start": "2017-11-04T07:30:00.000Z",
                    "utc_old_finish": "2017-11-04T08:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509002372
                },
                {
                    "id": 119,
                    "name": "test",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 112,
                    "recurring_type": "weekly",
                    "until": "never",
                    "until_date": null,
                    "repeat_every": 1,
                    "repeat_by": "4,5,6",
                    "my_note": "",
                    "old_head_id": 112,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-09T07:30:00.000Z",
                    "utc_finish": "2017-11-09T08:30:00.000Z",
                    "utc_old_start": "2017-11-09T07:30:00.000Z",
                    "utc_old_finish": "2017-11-09T08:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509002372
                },
                {
                    "id": 174,
                    "name": "Test event",
                    "description": "",
                    "where": "",
                    "all_day": true,
                    "recurring_type": "not_repeat",
                    "my_note": null,
                    "old_head_id": null,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-10-29T12:00:00.000Z",
                    "utc_finish": "2017-10-29T13:00:00.000Z",
                    "utc_old_start": null,
                    "utc_old_finish": null,
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1509012877
                }
            ],
            "requested_at": 847478097
        }

#### Create a calendar [POST]


+ Attributes (object)
    + `calendar[name]` (string) - Name of the calendar.
    + `calendar[owner_type]` (enum[string], required) - Type of the owner of the calendar.
        + members
            + `User`
            + `Space`
    + `calendar[owner_id]` (uuid, required) - Id of the owner of the calendar.

+ Request (application/json)

        {
            "calendar[name]": "A new personal calendar",
            "calendar[owner_type]": "User",
            "calendar[owner_id]": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150"
        }

+ Response 201 (application/json)

        {
            "calendar": {
                "id": 113,
                "owner_type": "User",
                "name": "A new personal calendar",
                "owner_id": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                "owner_name": "Personal",
                "display_name": "A new personal calendar (Personal)",
                "can_manage": true,
                "can_create_event": true
            }
        }

### Calendar [/calendar/calendar/{calendar_id}]

#### Delete a calendar [DELETE]

+ Parameters
    + `calendar_id` (number, required) - Id of the calendar.

+ Attributes
    + `move_events` (boolean) - Whether to move events to a new calendar.
    + `new_cal_id` (number) - Id of the new calendar for the moving events.

+ Request Delete together with all the events inside (application/json)

        {}

+ Response 200 (application/json)

        {
            "id": 113
        }

+ Request Delete and move events to another calendar (application/json)

        {
            "move_events": true,
            "new_cal_id": 112
        }

+ Response 200 (application/json)

        {
            "old_cal_id": 114,
            "new_cal_id": 112
        }

### Events [/calendar/calendar/{calendar_id}/event]

#### Create an event [POST]

+ Parameters
    + `calendar_id` (number, required) - Id of the calendar.

+ Attributes
:[](calendar/recurrence.apib)

+ Request With no recurrence (application/json)

        {
            "event[name]": "My first event!!!",
            "event[all_day]": true,
            "event[date_start]": "07/11/2017",
            "event[date_finish]": "07/11/2017",
            "event[time_start]": "12:00am",
            "event[time_finish]": "12:00am"
        }

+ Response 201 (application/json)

        {
            "events": {
                "id": 1,
                "name": "My first event!!!",
                "description": "",
                "where": "",
                "all_day": true,
                "recurring_type": "not_repeat",
                "my_note": null,
                "old_head_id": null,
                "calendar_id": 7,
                "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                "utc_start": "2017-11-07T12:00:00.000Z",
                "utc_finish": "2017-11-07T13:00:00.000Z",
                "utc_old_start": null,
                "utc_old_finish": null,
                "can_save": true,
                "can_delete": true,
                "timestamp": 1508398190
            }
        }

+ Request With recurrence (application/json)

        {
            "event[name]": "My first recurrence",
            "event[date_start]": "07/11/2017",
            "event[time_start]": "8:00am",
            "event[date_finish]": "07/11/2017",
            "event[time_finish]": "9:00am",
            "event[recurring_type]": "weekly",
            "event[until]": "never",
            "event[repeat_every]": 1,
            "event[until_date]": "",
            "event[where]": "",
            "event[description]": "",
            "event[repeat_by]": 2,
            "event[all_day]": false
        }

+ Response 201 (application/json)

        {
            "events": [
                {
                    "id": 65,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 64,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 64,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-08T08:30:00.000Z",
                    "utc_finish": "2017-11-08T09:30:00.000Z",
                    "utc_old_start": "2017-11-08T08:30:00.000Z",
                    "utc_old_finish": "2017-11-08T09:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508400561
                },
                {
                    "id": 66,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 64,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 64,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-15T08:30:00.000Z",
                    "utc_finish": "2017-11-15T09:30:00.000Z",
                    "utc_old_start": "2017-11-15T08:30:00.000Z",
                    "utc_old_finish": "2017-11-15T09:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508400561
                },
                {
                    "id": 67,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 64,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 64,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-22T08:30:00.000Z",
                    "utc_finish": "2017-11-22T09:30:00.000Z",
                    "utc_old_start": "2017-11-22T08:30:00.000Z",
                    "utc_old_finish": "2017-11-22T09:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508400561
                },
                {
                    "id": 68,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 64,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 64,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-29T08:30:00.000Z",
                    "utc_finish": "2017-11-29T09:30:00.000Z",
                    "utc_old_start": "2017-11-29T08:30:00.000Z",
                    "utc_old_finish": "2017-11-29T09:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508400561
                },
                {
                    "id": 69,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 64,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 64,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-12-06T08:30:00.000Z",
                    "utc_finish": "2017-12-06T09:30:00.000Z",
                    "utc_old_start": "2017-12-06T08:30:00.000Z",
                    "utc_old_finish": "2017-12-06T09:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508400561
                },
                {
                    "id": 70,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 64,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 64,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-12-13T08:30:00.000Z",
                    "utc_finish": "2017-12-13T09:30:00.000Z",
                    "utc_old_start": "2017-12-13T08:30:00.000Z",
                    "utc_old_finish": "2017-12-13T09:30:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508400561}],
                    "head_event": {
                    "id": 64,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": true,
                    "head_id": null,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": null,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-08T08:30:00.000Z",
                    "utc_finish": "2017-11-08T09:30:00.000Z",
                    "utc_old_start": null,
                    "utc_old_finish": null,
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508400561
                }
            ]
        }


### Event [/calendar/calendar/{calendar_id}/event/{event_id}]

#### Retrieve an event [GET]

+ Parameters
    + `calendar_id` (number, required) - Id of the calendar.
    + `event_id` (number, required) - Id of the event.

+ Request (application/json)

        {}

+ Response 200 (application/json)

        {
            "filter": {
                "enabled": [7],
                "userSetting": [0]
            },
            "cal_info": [
                {
                    "id": 7,
                    "owner_type": "User",
                    "name": "Test personal calendar",
                    "owner_id": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "owner_name": "Personal",
                    "display_name": "Test personal calendar (Personal)",
                    "can_manage": true,
                    "can_create_event": true
                }
            ],
            "spaces_permission": {
                "326ee7a7-2c7c-4af0-9eb6-3f79b90dae92": true,
                "b1d9b3bf-6cef-44c3-9382-4b32f7f2cd79": true
            },
            "event": {
                "id": 174,
                "name": "Test event",
                "description": "",
                "where": "",
                "all_day": true,
                "recurring_type": "not_repeat",
                "my_note": null,
                "old_head_id": null,
                "calendar_id": 7,
                "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                "utc_start": "2017-10-29T12:00:00.000Z",
                "utc_finish": "2017-10-29T13:00:00.000Z",
                "utc_old_start": null,
                "utc_old_finish": null,
                "can_save": true,
                "can_delete": true,
                "timestamp": 1509012877
            },
            "head_event": null,
            "recurring": []
        }

#### Update an event [PUT]

+ Parameters
    + `calendar_id` (number, required) - Id of the calendar.
    + `event_id` (number, required) - Id of the event.

+ Attributes
    + `event[future]` (boolean) - Whether to update events in the series from this event on.
    + `event[all]` (boolean) - Whether to update the entire series.
:[](calendar/recurrence.apib)

+ Request With no recurrence (application/json)

        {
            "event[name]": "My first event!!! (Edited)",
            "event[time_start]": "12:00pm",
            "event[time_finish]": "1:00pm",
            "event[until]": "never",
            "event[repeat_every]": 1,
            "event[until_date]": "",
            "event[invite_others]": "",
            "event[see_guest_list]": "",
            "event[my_note]": "",
            "event[repeat_by]": ""
        }

+ Response 200 (application/json)

        {
            "events":[
                {
                    "id": 1,
                    "name": "My first event!!! (Edited)",
                    "description": "",
                    "where": "",
                    "all_day": true,
                    "recurring_type": "not_repeat",
                    "my_note": "",
                    "old_head_id": null,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-07T12:00:00.000Z",
                    "utc_finish": "2017-11-07T13:00:00.000Z",
                    "utc_old_start": null,
                    "utc_old_finish": null,
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508401619
                }
            ]
        }

+ Request With recurrence and for future (application/json)

        {
            "event[date_start]": "22/11/2017",
            "event[time_start]": "",
            "event[date_finish]": "22/11/2017",
            "event[time_finish]": "",
            "event[all_day]": true,
            "event[repeat_every]": 1,
            "event[until_date]": "13/12/2017",
            "event[future]": true
        }

+ Response 200 (application/json)

        {
            "events": [
                {
                    "id": 71,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": true,
                    "head_flag": false,
                    "head_id": 67,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 67,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-22T12:00:00.000Z",
                    "utc_finish": "2017-11-22T13:00:00.000Z",
                    "utc_old_start": "2017-11-22T12:00:00.000Z",
                    "utc_old_finish": "2017-11-22T13:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508402510
                },
                {
                    "id": 72,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": true,
                    "head_flag": false,
                    "head_id": 67,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 67,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-29T12:00:00.000Z",
                    "utc_finish": "2017-11-29T13:00:00.000Z",
                    "utc_old_start": "2017-11-29T12:00:00.000Z",
                    "utc_old_finish": "2017-11-29T13:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508402510
                },
                {
                    "id": 73,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": true,
                    "head_flag": false,
                    "head_id": 67,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 67,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-12-06T12:00:00.000Z",
                    "utc_finish": "2017-12-06T13:00:00.000Z",
                    "utc_old_start": "2017-12-06T12:00:00.000Z",
                    "utc_old_finish": "2017-12-06T13:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508402510},
                {
                    "id": 74,
                    "name": "Recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": true,
                    "head_flag": false,
                    "head_id": 67,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-13",
                    "repeat_every": 1,
                    "repeat_by": "3",
                    "my_note": "",
                    "old_head_id": 67,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-12-13T12:00:00.000Z",
                    "utc_finish": "2017-12-13T13:00:00.000Z",
                    "utc_old_start": "2017-12-13T12:00:00.000Z",
                    "utc_old_finish": "2017-12-13T13:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508402510
                }
            ],
            "head_event":    {
                "id": 67,
                "name": "Recurrent event",
                "description": "",
                "where": "",
                "all_day": true,
                "head_flag": true,
                "head_id": null,
                "recurring_type": "weekly",
                "until": "to_date",
                "until_date": "2017-12-13",
                "repeat_every": 1,
                "repeat_by": "3",
                "my_note": "",
                "old_head_id": null,
                "calendar_id": 7,
                "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                "utc_start": "2017-11-22T12:00:00.000Z",
                "utc_finish": "2017-11-22T13:00:00.000Z",
                "utc_old_start": null,
                "utc_old_finish": null,
                "can_save": true,
                "can_delete": true,
                "timestamp": 1508402510
            }
        }

+ Request With recurrence and for the entire series (application/json)

        {
            "event[date_start]": "16/11/2017",
            "event[time_start]": "10:00am",
            "event[date_finish]": "16/11/2017",
            "event[time_finish]": "11:00am",
            "event[repeat_every]": 1,
            "event[until_date]": "14/12/2017",
            "event[invite_others]": "",
            "event[see_guest_list]": "",
            "event[all_day]": false,
            "event[all]": true
        }

+ Response 200 (application/json)

        {
            "events":[
                {
                    "id": 82,
                    "name": "Another recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 75,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-14",
                    "repeat_every": 1,
                    "repeat_by": "4",
                    "my_note": "",
                    "old_head_id": 75,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-09T00:00:00.000Z",
                    "utc_finish": "2017-11-09T00:00:00.000Z",
                    "utc_old_start": "2017-11-09T00:00:00.000Z",
                    "utc_old_finish": "2017-11-09T00:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508406018
                },
                {
                    "id": 83,
                    "name": "Another recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 75,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-14",
                    "repeat_every": 1,
                    "repeat_by": "4",
                    "my_note": "",
                    "old_head_id": 75,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-16T00:00:00.000Z",
                    "utc_finish": "2017-11-16T00:00:00.000Z",
                    "utc_old_start": "2017-11-16T00:00:00.000Z",
                    "utc_old_finish": "2017-11-16T00:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508406018
                },
                {
                    "id": 84,
                    "name": "Another recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 75,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-14",
                    "repeat_every": 1,
                    "repeat_by": "4",
                    "my_note": "",
                    "old_head_id": 75,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-23T00:00:00.000Z",
                    "utc_finish": "2017-11-23T00:00:00.000Z",
                    "utc_old_start": "2017-11-23T00:00:00.000Z",
                    "utc_old_finish": "2017-11-23T00:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508406018
                },
                {
                    "id": 85,
                    "name": "Another recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 75,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-14",
                    "repeat_every": 1,
                    "repeat_by": "4",
                    "my_note": "",
                    "old_head_id": 75,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-11-30T00:00:00.000Z",
                    "utc_finish": "2017-11-30T00:00:00.000Z",
                    "utc_old_start": "2017-11-30T00:00:00.000Z",
                    "utc_old_finish": "2017-11-30T00:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508406018
                },
                {
                    "id": 86,
                    "name": "Another recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 75,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-14",
                    "repeat_every": 1,
                    "repeat_by": "4",
                    "my_note": "",
                    "old_head_id": 75,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-12-07T00:00:00.000Z",
                    "utc_finish": "2017-12-07T00:00:00.000Z",
                    "utc_old_start": "2017-12-07T00:00:00.000Z",
                    "utc_old_finish": "2017-12-07T00:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508406018
                },
                {
                    "id": 87,
                    "name": "Another recurrent event",
                    "description": "",
                    "where": "",
                    "all_day": false,
                    "head_flag": false,
                    "head_id": 75,
                    "recurring_type": "weekly",
                    "until": "to_date",
                    "until_date": "2017-12-14",
                    "repeat_every": 1,
                    "repeat_by": "4",
                    "my_note": "",
                    "old_head_id": 75,
                    "calendar_id": 7,
                    "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                    "utc_start": "2017-12-14T00:00:00.000Z",
                    "utc_finish": "2017-12-14T00:00:00.000Z",
                    "utc_old_start": "2017-12-14T00:00:00.000Z",
                    "utc_old_finish": "2017-12-14T00:00:00.000Z",
                    "can_save": true,
                    "can_delete": true,
                    "timestamp": 1508406018
                }
            ],
            "head_event":{
                "id": 75,
                "name": "Another recurrent event",
                "description": "",
                "where": "",
                "all_day": false,
                "head_flag": true,
                "head_id": null,
                "recurring_type": "weekly",
                "until": "to_date",
                "until_date": "2017-12-14",
                "repeat_every": 1,
                "repeat_by": "4",
                "my_note": "",
                "old_head_id": null,
                "calendar_id": 7,
                "created_by": "bdc6aced-f7d0-465d-9d8b-6629d1cfd150",
                "utc_start": "2017-11-09T00:00:00.000Z",
                "utc_finish": "2017-11-09T00:00:00.000Z",
                "utc_old_start": null,
                "utc_old_finish": null,
                "can_save": true,
                "can_delete": true,
                "timestamp": 1508406018
            },
            "head_id": 75,
            "first_entity": 82,
            "last_entity": 87
        }

#### Delete an event [DELETE]

+ Parameters
    + `calendar_id` (number, required) - Id of the calendar.
    + `event_id` (number, required) - Id of the event.

+ Attributes
    + `after` (boolean) - Whether to delete event in the series from this event on.
    + `all` (boolean) - Whether to delete the entire series.

+ Request With no recurrence (application/json)

        {}

+ Response 200 (application/json)

        {}

+ Request With recurrence and for future (application/json)

        {
            "after": true
        }

+ Response 200 (application/json)

        {
            "head_id": 90,
            "first_entity": 91,
            "last_entity": 91
        }

+ Request With recurrence and for future (application/json)

        {
            "after": true
        }

+ Response 200 (application/json)

        {
            "head_id": 90,
            "first_entity": 91,
            "last_entity": 91
        }


+ Request With recurrence and for the entire series (application/json)

        {
            "all": true
        }

+ Response 200 (application/json)

        {}
