## Group General

### User connections [GET /people/connections]

- Request (application/json)

- Response 200 (application/json)
    - Attributes (object)
        - `id` (string) - user ID
        - `login` (string) - user login name
        - `jid` (string) - Jabber/XMPP ID of the user
        - `mutual_spaces` (array) - array of spaces that are shared by user and space member
        - `name` (string) - name of the user
        - `status_message` (string) - status message of the user
