## Group Self Profile

### Self Profile [/people/profile]

#### Show [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes (object)
:[](profile/profile.apib)

#### Update names [PUT]

+ Request (application/json)

    + Attributes (object)
        + `user` (object)
            + `first_name` (string) - at least 2 characters long
            + `last_name` (string) - at least 2 characters long

+ Response 200 (application/json)

    + Attributes (object)
:[](profile/profile.apib)

#### Set `login` [PUT /people/users/{user_id}]

+ Parameters
    + `user_id` (uuid) - UUID of the current User

+ Request (application/json)

    + Attributes (object)
        + `login` (string) - must be between 7 to 40 characters long

+ Response 403 (application/json)

+ Response 422 (application/json)

+ Response 200 (application/json)

    + Attributes (object)
