## Group Space

### Spaces [/spaces]

#### Index [GET]

- Request (application/json)

- Response 200 (application/json)
    - Attributes (object)
        - spaces (array[Space]) - list of spaces

    - Body

            :[](fixture:spaces.json)

#### Create [POST]

- Request (application/json)
    - Attributes (object)
        - space (Space) - new space attributes

- Response 200 (application/json)
    - Attributes (object)
        - space (Space) - created space

    - Body

            :[](fixture:space.json)

#### Show [GET /spaces/{space_id}]

- Parameters
    - `space_id` (uuid)

- Request (application/json)

- Response 200 (application/json)
    - Attributes (object)
        - space (Space) - retrieved space

    - Body

            :[](fixture:space.json)

#### Update [PUT /spaces/{space_id}]

- Parameters
    - `space_id` (uuid)

- Request (application/json)
    - Attributes (object)
        - space (Space) - space update

- Response 200 (application/json)
    - Attributes (object)
        - space (Space) - updated space

    - Body

            :[](fixture:space.json)

#### Delete [DELETE /spaces/{space_id}]

- Parameters
    - `space_id` (uuid)

- Request (application/json)

- Response 200 (application/json)
