## Group Space Category

### Space Categories [/space_categories]

#### Index [GET]

- Request (application/json)

- Response 200 (application/json)
    - Attributes (array[object])
        - (object)
            - `id`: 2 (id) - ID of the category
            - `name`: Architecture and Zoology (string) - English name of the category
