## Group Space

### Spaces [/spaces]

#### Index [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (object)
        + `id` (number) - space ID
        + `name` (string) - name of the space
        + `joined_at` (string) - date of when the user joined the space
        + `created_at` (string) - date of when the space was created
        + `owned_roles` (array) - array of objects representing a space role related to the space
        + `access` (string) - options
        + `active` (boolean) - whether the space is active or not
        + `owner` (boolean) - whether the user is the owner of the space
        + `role_name` (string) - role of the current user, can be `Administrator`, `Member`, or `Read only`
        + `description` (string) - description of the space
        + `members_count` (number) - number of members in the space
        + `visibility` (string) - visibility of the space, can be `visible`, `visible_name`, or `invisible`
