## Group Authentication

### Log in [POST /login]

+ Request (application/x-www-form-urlencoded)
    + Attributes
        + `utf8` (string, required) - Any string containing characters specific to UTF-8, e.g. `"✓"`
        + `authenticity_token` (string, required) - CSRF prevention
        + `invitation_code` (string, required) - invitation code
        + `return_to` (string, required) - URL redirection parameter
        + `username` (string, required) - username or email
        + `password` (string, required) - password
        + `remember_me` (boolean, required) - `1` for true or `0` for false

+ Response 302 (text/html; charset=utf-8)
    On successful login, server responds with redirection to URL passed as
    `return_to` option in request.

+ Response 200 (text/html; charset=utf-8)
    Incorrect user name or password.

+ Response 200 (text/html)
    + Attributes (object)

### Log out [DELETE /logout]

+ Request (application/x-www-form-urlencoded)
    + Attributes

+ Response 204 (text/html)
    User has been logged out.

+ Response 302 (text/html)
    User was not logged in.
