        - `user` (object)
            - `first_name`       (string)
            - `id`               (uuid)
            - `last_name`        (string)
            - `indigo_user_id`   (uuid)
            - `name`             (string)
            - `fields`           (array[object])
                - `name`             (string)
                - `base_name`        (string)
                - `title`            (string)
                - `type`             (string)
                - `value`            (string, nullable)
                - `value_type`       (string, nullable)
                - `value_type_title` (string, nullable)
                - `visibility`       (string)
            - `avatar` (object, nullable)
                - `id`                           (number)
                - `last_resize_info_for_cropper` (string)
                - `thumb_width`                  (number)
                - `thumb_height`                 (number)

